name: Regression test


on:
  push:
  workflow_dispatch:

jobs:
  run-all-test:
    runs-on: ubuntu-latest
    env:
      EMAIL_FOR_LOGIN_CALL: ${{secrets.EMAIL}}
      PASSWORD_FOR_LOGIN_CALL: ${{secrets.PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'


      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Set UP All and run test
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

      - name: End of tst
      - run: echo "Regresion test finished"



