name: smoke

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  second-job:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
  third-job:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Set UP All and run test
      run: mvn clean install
